import { useEffect } from 'react';
import './Popup.scss';
import linkStyles from './link.module.scss';
import { makeLocalStorage } from 'shared/factories/cache/makeLocalStorage';
import { useStorageState } from 'shared/hooks/useStorageState';

export const Popup = () => {
  const [counter, setCounter] = useStorageState('counter');
  const link = 'https://github.com/guocaoyi/create-chrome-ext';
  const storage = makeLocalStorage();

  const minus = () => {
    if (counter === 0) return;

    setCounter(counter + 1);
  };

  const add = () => {
    setCounter(counter + 1);
  };

  useEffect(() => {
    storage.get(['counter']).then(({ counter }) => {
      console.log(counter);
    });
  }, [storage]);

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={counter <= 0}>
          -
        </button>
        <label>{counter}</label>
        <button onClick={add}>+</button>
      </div>
      <a
        href={link}
        target="_blank"
        rel="noreferrer"
        className={linkStyles.testOne}
      >
        generated by create-chrome-ext
      </a>
    </main>
  );
};

export default Popup;
